import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs/app-beta'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  parallel,
  parallel2,
}: {
  children: React.ReactNode
  parallel: React.ReactNode
  parallel2: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <div>children:</div>

          {children}

          <div>parallel:</div>

          <SignedIn>{parallel}</SignedIn>

          <div>parallel2:</div>

          <SignedOut>{parallel2}</SignedOut>
        </body>
      </ClerkProvider>
    </html>
  )
}
