import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs/app-beta'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>children:</div>

        {children}

        <ClerkProvider>test...</ClerkProvider>
      </body>
    </html>
  )
}
