import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  parallel,
  parallel2,
}: {
  children: React.ReactNode
  parallel: React.ReactNode
  parallel2: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>children:</div>

        {children}

        <div>parallel:</div>

        {parallel}

        <div>parallel2:</div>

        {parallel2}
      </body>
    </html>
  )
}
